### ISSUE TITLE
Permissions on local directory

### ISSUE THREAD

**Issue by sharonjl** [usmanhalalit/gost#1]
I can't access *local* directories created by the library, it seems as though the directories are given the permission 644 instead of 777.

**Comment by usmanhalalit** [comment]
@sharonjl Thanks for reporting.
Which OS are you in? Can't access means you can't access the dirs using the library?

Does https://github.com/usmanhalalit/gost/pull/2 solve your issue?

**Comment by sharonjl** [comment]
I am on maxOS 10.1. Yes, #2 solves the problem. I am not too familiar with Unix permissions, this is what I noticed:
- 644: Locks the directory and the library can't access the directory as well (or create files/nested dirs inside). I don't think this is the right permission when creating a directory.
- 755: Locks the directory for process/users that didn't create the directory. The library was able to access the directory (and create files/dirs inside of it), but I couldn't access it from the terminal.
- 777: Gives everyone all the access

**Comment by usmanhalalit** [comment]
Thanks, merged!
