### ISSUE TITLE
Nice work! Can you do the https s3 api connector using fasthttp?

### ISSUE THREAD

**Issue by hiqsociety** [usmanhalalit/gost#7]
1. Nice work! Can you do the https s3 api connector using fasthttp?
2. I see a lot of potential to connect a lightsail instance to aws EFS to save cost on api calls for s3.
then there will be huge adoption using this software.

great work by the way!

**Comment by usmanhalalit** [comment]
Thanks @hiqsociety! Tbh, I don't really have much to add and maintain these but I do appreciate your feedback.
