### ISSUE TITLE
Recursively directory creation not work

### ISSUE THREAD

**Issue by trixden** [usmanhalalit/gost#8]
### Code:

```golang
var Directory gost.Directory = initDirectory()

func initDirectory() gost.Directory {
        if dir, err := local.New(local.Config{
		BasePath: "/path/to/public",
	}); err != nil {
		log.Fatal(err.Error())
	} else {
		return dir
	}

	return nil
}

func MakeTestFile() {
	newFile := Directory.File("test/test/test.txt")

	if !newFile.Exists() {
		log.Println("File does not exist")
		if err := newFile.Directory().Create(); err != nil {
			log.Fatal(err.Error())
		}
	}

	if n, err := newFile.Write([]byte("Test txt")); err != nil {
		log.Fatal(err.Error())
	} else if n == 0 {
		log.Println("Null bytes writed")
	}
}
```

### Problem:

When I try to create a folder in a subdirectory higher than one level, I get the error on `newFile.Directory().Create()`:

```
File does not exist
Fatal: mkdir /path/to/public/uploads/test/test: no such file or directory
```
Because there is no `test` folder in the `uploads` folder. What can I do in such a situation? If I create folders using `os`, I cannot use S3 in production

**Comment by usmanhalalit** [comment]
Thanks for reporting that! I don't think anything was implemented for this scenario.
Does it work if you create all the directories before hand `Directory.Directory("test").Create()`? If so, you might have to stick with that.
